import 'bootstrap/dist/css/bootstrap.min.css';
import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Token from "@/components/Token";
import Who from "@/components/Who";
import Famous from "@/components/Famous";
import Legend from "@/components/Legend";
import Roodmap from "@/components/Roodmap";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Skooma</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Header />
        <Token />
        <Who />
        <Famous />
        <Legend />
        <Roodmap />
        <Footer />
      </>
    </>
  );
}
